### ISSUE TITLE
 AttributeError: 'StableDiffusionProcessingImg2Img' object has no attribute 'infotexts'

### ISSUE THREAD

**Issue by maxi1134** [ilian6806/stable-diffusion-webui-eyemask#17]
Hi there!

I get this error when trying to use this script:

`
Arguments: ('task(sz3czlhea1shfcf)', 'A realistic face', '', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 0, '', '', [], 4, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, True, 0, '', '', 20, True, 20, True, 4, 0.4, 7, 512, 512, True, 88, False, 'None') {}
Traceback (most recent call last):
  File "/home/maxi1134/stable-diffusion/stable-diffusion-webui/modules/call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "/home/maxi1134/stable-diffusion/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/home/maxi1134/stable-diffusion/stable-diffusion-webui/modules/txt2img.py", line 54, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "/home/maxi1134/stable-diffusion/stable-diffusion-webui/modules/scripts.py", line 441, in run
    processed = script.run(p, *script_args)
  File "/home/maxi1134/stable-diffusion/stable-diffusion-webui/extensions/stable-diffusion-webui-eyemask/scripts/em_script.py", line 35, in run
    return self.eye_mask_core.execute(*args, **kwargs)
  File "/home/maxi1134/stable-diffusion/stable-diffusion-webui/extensions/stable-diffusion-webui-eyemask/scripts/eyemask/script.py", line 217, in execute
    p.infotexts.append(updated_info)
AttributeError: 'StableDiffusionProcessingImg2Img' object has no attribute 'infotexts'
`

**Comment by ilian6806** [comment]
Hi!

Are you on the latest version of AUTOMATIC1111/stable-diffusion-webui ?

**Comment by maxi1134** [comment]
Hi there!

These are the versions I am using:

`version: v1.3.0  •  python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: N/A  •  gradio: 3.31.0  •  checkpoint: 6ce0161689`

**Comment by davehornik** [comment]
Getting the same.

```python
Arguments: ('task(v9485six6dxoel0)', '(cybernetics by emb-rrf2:1), full body portrait of a girl from profile, <lora:DI_belle_delphine_v1:0.4>, photorealistic, absurdres, pastel style, (RFKTR_fshnsta:1.3), wearing collar, nsfw', 'bad_pictures,  easynegative, By bad artist -neg_2, signature, text, letter', [], 30, 18, False, False, 1, 1, 6, 1214571347.0, -1.0, 0, 0, 0, False, 696, 696, False, 0.35, 1.75, '4x-UltraSharp', 0, 0, 0, 0, '', '', [], 6, False, {'ad_model': 'face_yolov8n.pt', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_weight': 1}, {'ad_model': 'None', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_weight': 1}, False, 7, 100, 'Constant', 0, 'Constant', 0, 4, <controlnet.py.UiControlNetUnit object at 0x0000014696428DC0>, <controlnet.py.UiControlNetUnit object at 0x0000014696428F10>, <controlnet.py.UiControlNetUnit object at 0x00000146964294B0>, <controlnet.py.UiControlNetUnit object at 0x0000014696429C60>, 0, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, False, False, '#000000', False, None, False, None, False, None, False, None, False, 50, True, 0, 'beautiful blue eyes, pastel style', 'bad_pictures,  easynegative, By bad artist -neg_2, signature, text, letter', 20, True, 30, True, 4, 0.4, 6, 696, 696, True, 88, False, 'None') {}
Traceback (most recent call last):
  File "D:\Stable WEBUI\stable-diffusion-webui\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "D:\Stable WEBUI\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\Stable WEBUI\stable-diffusion-webui\modules\txt2img.py", line 54, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "D:\Stable WEBUI\stable-diffusion-webui\modules\scripts.py", line 441, in run
    processed = script.run(p, *script_args)
  File "D:\Stable WEBUI\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\em_script.py", line 35, in run
    return self.eye_mask_core.execute(*args, **kwargs)
  File "D:\Stable WEBUI\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\script.py", line 217, in execute
    p.infotexts.append(updated_info)
AttributeError: 'StableDiffusionProcessingImg2Img' object has no attribute 'infotexts'

```

**Comment by ilian6806** [comment]
Can you give me some more info like the steps you are doing and I will try to fix it tomorrow

**Comment by maxi1134** [comment]
![image](https://github.com/ilian6806/stable-diffusion-webui-eyemask/assets/1342643/a01e55b1-e3f5-4688-aec1-07edacbecab5)
The error still happens for me after an update unfortunately

**Comment by ilian6806** [comment]
https://prnt.sc/CYafu88M3ZGa

Can you check if you have this part of the code?
