### ISSUE TITLE
Mask always comes out black for some reason

### ISSUE THREAD

**Issue by dragos240** [ilian6806/stable-diffusion-webui-eyemask#22]
I'm trying to use your extension, but the masking seems to not be working correctly, because when I enable and generate, the mask layer that's generated is entirely black and the "fixed" layer looks strange.

For example, here is the original generation:
![00028-2671658666](https://github.com/ilian6806/stable-diffusion-webui-eyemask/assets/704081/8269b8f9-59d3-49ea-8f1e-82311a242b4f)

Here's the "fixed" version:
![00029-2671658666 0](https://github.com/ilian6806/stable-diffusion-webui-eyemask/assets/704081/4f2679e9-7228-4b5e-b4a1-f5ff21ad3e41)

And here is the mask:
![00030-2671658666 0](https://github.com/ilian6806/stable-diffusion-webui-eyemask/assets/704081/b7db3cdc-5ab4-4071-8771-821668a42f1a)

As you can see, I'm getting some strange results. For clarity, I'm not using the default model, but instead using [yiffymix-v3](https://civitai.com/models/3671/yiffymix) and my stable diffusion is the [directml fork](https://github.com/lshqqytiger/stable-diffusion-webui-directml) because I use an AMD card (a Radeon RX 6800 XT).

Here are the generation details that can be used to reproduce the problem:
<details><summary>Generation data</summary>
uploaded on e621, ((by Wildering, by Foxovh, by Disney)), Zootopia, solo (((nick wilde))) with ((neck tuft)) and (fluffy tail) and ((clear navy blue eyes)), ((wear blue hawaii floral shirt with grey pants)), BREAK, (detailed red fox nick wilde), (detailed lighting), ((detailed fluffy fur)), BREAK, ((sitting at island with plant and water on sunny day)), (cinematic lighting), ((detailed background)), ((depth of field)), (half body shadow), (((looking at viewer))), ((half-length portrait)), (high-angle view), ((three-quarter view)), [backlighting], [detailed ambient light], [gray natural lighting], [ambient light on the belly], [realistic proportions], [explicit content, adult, nsfw], [sharp focus], (questionable content), (shaded), (hi res), ((masterpiece))
Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 5, Seed: 2671658666, Size: 512x512, Model hash: 3cea5ea114, Model: yiffymix_3, Denoising strength: 0.4, em_mask_prompt: "clear eyes, detailed eyes", em_mask_negative_prompt: blurry eyes, em_mask_padding: 20, em_mask_steps: 20, em_mask_blur: 4, em_denoising_strength: 0.4, em_cfg_scale: 7, em_width: 512, em_height: 512, em_inpaint_full_res: True, em_inpaint_full_res_padding: 88, em_mask_prompt_final: "clear eyes, detailed eyes"
</details>

**Comment by ilian6806** [comment]
If you get a black mask, it means that no face/eyes are found. I`m afraid these algorithms work primarily for human faces...
