### ISSUE TITLE
Prompt for eyes not get used

### ISSUE THREAD

**Issue by JokerGT** [ilian6806/stable-diffusion-webui-eyemask#23]
Im trying to replace the face with your plugin but for some reason, it always uses my original prompt and not the prompt i entered for the eye mask. how can i force your plugin to use my new prompt and not the original ?

when i use my new prompt with inpaint, it works fine

thanks

great work

**Comment by ilian6806** [comment]
Eyes prompt must be used. Are you sure about this?

**Comment by JokerGT** [comment]
don't mind, it was my fault
