### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'hide_samplers'

### ISSUE THREAD

**Issue by mikecastrodemaria** [ilian6806/stable-diffusion-webui-eyemask#27]
Hi, I have this error after activate the extension : 

*** stderr: /.../venv/lib/python3.10/site-packages/pytorch_lightning/utilities/distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
***   rank_zero_deprecation(
*** Traceback (most recent call last):
***   File "/.../extensions/stable-diffusion-webui-eyemask/install.py", line 6, in <module>
***     from modules.sd_models import model_hash
***   File "/.../modules/sd_models.py", line 17, in <module>
***     from modules import paths, shared, modelloader, devices, script_callbacks, sd_vae, sd_disable_initialization, errors, hashes, sd_models_config, sd_unet, sd_models_xl, cache, extra_networks, processing, lowvram, sd_hijack
***   File "/.../modules/sd_vae.py", line 5, in <module>
***     from modules import paths, shared, devices, script_callbacks, sd_models, extra_networks, lowvram, sd_hijack, hashes
***   File "/.../modules/sd_hijack.py", line 5, in <module>
***     from modules import devices, sd_hijack_optimizations, shared, script_callbacks, errors, sd_unet
***   File "/.../modules/sd_hijack_optimizations.py", line 13, in <module>
***     from modules.hypernetworks import hypernetwork
***   File "/.../modules/hypernetworks/hypernetwork.py", line 13, in <module>
***     from modules import devices, sd_models, shared, sd_samplers, hashes, sd_hijack_checkpoint, errors
***   File "/.../modules/sd_samplers.py", line 59, in <module>
***     set_samplers()
***   File "/.../modules/sd_samplers.py", line 44, in set_samplers
***     samplers_hidden = set(shared.opts.hide_samplers)
*** AttributeError: 'NoneType' object has no attribute 'hide_samplers'

System Information

OS Name: Darwin 22.6.0
OS Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
WebUI Version: https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5ef669de080814067961f28357256e8fe27544f4
Torch Version: 2.0.1
Python Version: 3.10.6 (v3.10.6:9c7b4bd164, Aug  1 2022, 17:13:48) [Clang 13.0.0 (clang-1300.0.29.30)]

CPU: arm
CPU Cores: 10/10

COMMANDLINE_ARGS (Divide by space)
--skip-torch-cuda-test --use-cpu all

**Comment by ilian6806** [comment]
I fixed this with last commit.
