### ISSUE TITLE
CUDA not working but detected, aiming to run Khoya_ss to make a LORA

### ISSUE THREAD

**Issue by GIadstone** [ilian6806/stable-diffusion-webui-eyemask#29]
Hi,

Spent lot of time to try to make khoya ss work, here is the final bug report : 

Please, i'm out of solutions, gpt4 to...

11:16:05-558597 INFO     Version: v22.1.1

11:16:05-564602 INFO     nVidia toolkit detected
11:16:07-182074 INFO     Torch 2.0.1+cu118
11:16:07-219997 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
11:16:07-221999 INFO     Torch detected GPU: NVIDIA GeForce RTX 2070 VRAM 8192 Arch (7, 5) Cores 36
11:16:07-224000 INFO     Verifying modules installation status from requirements_windows_torch2.txt...
11:16:07-227003 INFO     Verifying modules installation status from requirements.txt...
11:16:09-833691 INFO     headless: False
11:16:09-837695 INFO     Load CSS...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
11:17:32-006690 INFO     Start training Dreambooth...
11:17:32-008692 INFO     Valid image folder names found in: C:/Users/adacr/Desktop/Kohya/LORA Training/Images
11:17:32-010702 INFO     Folder 15_Emy : steps 150
11:17:32-011703 INFO     max_train_steps (150 / 1 / 1 * 30 * 1) = 4500
11:17:32-012704 INFO     stop_text_encoder_training = 0
11:17:32-013698 INFO     lr_warmup_steps = 450
11:17:32-014706 INFO     Saving training config to C:/Users/adacr/Desktop/Kohya/LORA
                         Training/model\EmyGladV1_20231113-111732.json...
11:17:32-016700 INFO     accelerate launch --num_cpu_threads_per_process=2 "./train_db.py" --enable_bucket
                         --min_bucket_reso=256 --max_bucket_reso=2048 --pretrained_model_name_or_path="D:/Stabble
                         diffusion/webui/models/Stable-diffusion/Realityllove.safetensors"
                         --train_data_dir="C:/Users/adacr/Desktop/Kohya/LORA Training/Images" --resolution="768,768"
                         --output_dir="C:/Users/adacr/Desktop/Kohya/LORA Training/model"
                         --logging_dir="C:/Users/adacr/Desktop/Kohya/LORA Training/log" --save_model_as=safetensors
                         --output_name="EmyGladV1" --lr_scheduler_num_cycles="30" --max_data_loader_n_workers="0"
                         --learning_rate="1e-05" --lr_scheduler="cosine" --lr_warmup_steps="450" --train_batch_size="1"
                         --max_train_steps="4500" --save_every_n_epochs="6" --mixed_precision="fp16"
                         --save_precision="fp16" --cache_latents --optimizer_type="AdamW8bit"
                         --max_data_loader_n_workers="0" --bucket_reso_steps=64 --xformers --bucket_no_upscale
                         --noise_offset=0.0
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `1`
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
prepare tokenizer
prepare images.
found directory C:\Users\adacr\Desktop\Kohya\LORA Training\Images\15_Emy contains 10 image files
No caption file found for 10 images. Training will continue without captions for these images. If class token exists, it will be used. / 10枚の画像にキャプションファイルが見つかりませんでした。これらの画像についてはキャプションなしで学習を 続行します。class tokenが存在する場合はそれを使います。
C:\Users\adacr\Desktop\Kohya\LORA Training\Images\15_Emy\EMY 10.png
C:\Users\adacr\Desktop\Kohya\LORA Training\Images\15_Emy\EMY 4.png
C:\Users\adacr\Desktop\Kohya\LORA Training\Images\15_Emy\EMY 5.jpg
C:\Users\adacr\Desktop\Kohya\LORA Training\Images\15_Emy\EMY 6.png
C:\Users\adacr\Desktop\Kohya\LORA Training\Images\15_Emy\EMY 7.png
C:\Users\adacr\Desktop\Kohya\LORA Training\Images\15_Emy\EMY 8.jpg... and 5 more
150 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 1
  resolution: (768, 768)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 2048
  bucket_reso_steps: 64
  bucket_no_upscale: True

  [Subset 0 of Dataset 0]
    image_dir: "C:\Users\adacr\Desktop\Kohya\LORA Training\Images\15_Emy"
    image_count: 10
    num_repeats: 15
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: Emy
    caption_extension: .caption

[Dataset 0]
loading image sizes.
100%|█████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 146.38it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (512, 512), count: 30
bucket 1: resolution (512, 768), count: 120
mean ar error (without repeats): 0.0
prepare accelerator
loading model for process 0/1
load StableDiffusion checkpoint: D:/Stabble diffusion/webui/models/Stable-diffusion/Realityllove.safetensors
UNet2DConditionModel: 64, 8, 768, False, False
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
Enable xformers for U-Net
[Dataset 0]
caching latents.
checking cache validity...
100%|██████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<?, ?it/s]
caching latents...
100%|██████████████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  4.67it/s]
prepare optimizer, data loader etc.
False

===================================BUG REPORT===================================
C:\Users\adacr\Desktop\Kohya\kohya_ss\kohya_ss\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

  warn(msg)
================================================================================
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 7.5.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary C:\Users\adacr\Desktop\Kohya\kohya_ss\kohya_ss\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
Traceback (most recent call last):
  File "C:\Users\adacr\Desktop\Kohya\kohya_ss\kohya_ss\train_db.py", line 488, in <module>
    train(args)
  File "C:\Users\adacr\Desktop\Kohya\kohya_ss\kohya_ss\train_db.py", line 171, in train
    _, _, optimizer = train_util.get_optimizer(args, trainable_params)
  File "C:\Users\adacr\Desktop\Kohya\kohya_ss\kohya_ss\library\train_util.py", line 3419, in get_optimizer
    import bitsandbytes as bnb
  File "C:\Users\adacr\Desktop\Kohya\kohya_ss\kohya_ss\venv\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\Users\adacr\Desktop\Kohya\kohya_ss\kohya_ss\venv\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\Users\adacr\Desktop\Kohya\kohya_ss\kohya_ss\venv\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\Users\adacr\Desktop\Kohya\kohya_ss\kohya_ss\venv\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\Users\adacr\Desktop\Kohya\kohya_ss\kohya_ss\venv\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "C:\Users\adacr\Desktop\Kohya\kohya_ss\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
Traceback (most recent call last):
  File "C:\Users\adacr\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\adacr\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\adacr\Desktop\Kohya\kohya_ss\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\adacr\Desktop\Kohya\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\Users\adacr\Desktop\Kohya\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "C:\Users\adacr\Desktop\Kohya\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\adacr\\Desktop\\Kohya\\kohya_ss\\kohya_ss\\venv\\Scripts\\python.exe', './train_db.py', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--pretrained_model_name_or_path=D:/Stabble diffusion/webui/models/Stable-diffusion/Realityllove.safetensors', '--train_data_dir=C:/Users/adacr/Desktop/Kohya/LORA Training/Images', '--resolution=768,768', '--output_dir=C:/Users/adacr/Desktop/Kohya/LORA Training/model', '--logging_dir=C:/Users/adacr/Desktop/Kohya/LORA Training/log', '--save_model_as=safetensors', '--output_name=EmyGladV1', '--lr_scheduler_num_cycles=30', '--max_data_loader_n_workers=0', '--learning_rate=1e-05', '--lr_scheduler=cosine', '--lr_warmup_steps=450', '--train_batch_size=1', '--max_train_steps=4500', '--save_every_n_epochs=6', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0']' returned non-zero exit status 1.

**Comment by ilian6806** [comment]
Not sure how this is related to the extension...
