### ISSUE TITLE
Try to solve "has no attribute 'hide_samplers'" why the result is bad ?

### ISSUE THREAD

**Issue by irfanshidqi** [ilian6806/stable-diffusion-webui-eyemask#33]
i try to debug and resolve the error about "hide_samplers" in

last line traceback error : 
1. this accour when i try to change this line in "sd-folder > modules > shared.py" :
opts = {'hide_samplers': []}  # Initialize opts with hide_samplers attribute as an empty list

Error : 
***     samplers_hidden = set(shared.opts.hide_samplers)
*** AttributeError: 'dict' object has no attribute 'hide_samplers'

and 

2. if i leave the code in "sd-folder > modules > shared.py" like : 
opts = None

Error : 
***     samplers_hidden = set(shared.opts.hide_samplers)
*** AttributeError: 'NoneType' object has no attribute 'hide_samplers'

3. last one i try to change the code in "sd-folder > modules > sd_samplers.py" : 
![image](https://github.com/ilian6806/stable-diffusion-webui-eyemask/assets/48230672/8dca3bfc-a637-4de5-aa84-b167b0f6ca35)

it is solve the error . but the result is like this and the result is kind a very bad :

![image](https://github.com/ilian6806/stable-diffusion-webui-eyemask/assets/48230672/63db5a81-0265-4a62-9395-b81c43610ee2)

**Comment by ilian6806** [comment]
I fixed this with the last commit. It was a dependency that is not used.
